### ISSUE TITLE
How to implement in frontend JS?

### ISSUE THREAD

**Issue by amarvora** [chillerlan/php-imagetiler#1]
Hello

Very first thank you for sharing this library and it's really really useful to me. Can you please tell me How we can use this slicing images in frontend JS? Because I am providing API to frontend. So if you have any idea for frontend JS logic or if you have any source link then please share with me. It would be the great help

Thank you

**Comment by codemasher** [comment]
Hi, i think it depends on what size of images you want to tile. Small images are usually processed quickly, so you could simply upload/process/zip/push to download. However, large images can take up to hours to process (depending on the settings), so it would make sense to just upload the image and run the tiling process in background and then notify the user in some way once tiling is done.
