### ISSUE TITLE
In Slicing image artefacts coming in between

### ISSUE THREAD

**Issue by amarvora** [chillerlan/php-imagetiler#2]
Hello

I have uploaded map slicing is working very nice but I noticed that some artefacts coming in between.. Some green color lines are coming in slicing image, Can you please tell me what could be the reason of that? 

I have attached slicing images here. so you can get idea. also attaching image of my code.

![image](https://user-images.githubusercontent.com/2888801/125971006-568993b2-3b7d-46fa-8c2e-92e67a7f85fa.png)
![7](https://user-images.githubusercontent.com/2888801/125971101-51e1111f-4b34-4fa7-bf45-c27c39da0727.png)

My code
![image](https://user-images.githubusercontent.com/2888801/125971741-11913138-d422-40d9-83a6-b3b2d456dcdf.png)

**Comment by codemasher** [comment]
To be honest, i have no idea where this line could come from - i don't see anything wrong with your code. Does running the [example code](https://github.com/chillerlan/php-imagetiler/blob/main/examples/imagetiler.php) with your image source produce the same result?

**Comment by amarvora** [comment]
Its strange, that i have same server but 2 different applications.. code is even same, but for one application its working absolutely fine. But for other applications i m facing this issue. Its wierd, and not getting what could the root cause of it.

**Comment by codemasher** [comment]
If it's working fine in one of your apps, then the root cause is probably not this library? I'm afraid i can't help you much here.

**Comment by amarvora** [comment]
I will explore more but thank you very much for responding.. i will do more deep research on it. Once again thank you very much 😊
