### ISSUE TITLE
Bump dependency on psr/log to newer version

### ISSUE THREAD

**Issue by pvodicka** [chillerlan/php-imagetiler#4]
Hello, is it possible to set dependency on psr/log to newer/newest version. Updating of some other packages is conflicting because of that.

**Comment by codemasher** [comment]
Hey, I haven't looked at this library in a long time and didn't expect someone actually using it 😆. I'll look into it as soon as I can - i guess it's not done with updating that one dependency alone.

**Comment by codemasher** [comment]
Ok I took a quick look, [updated some things](https://github.com/chillerlan/php-imagetiler/actions/runs/8381013226) and tagged a new version: [3.1.0](https://github.com/chillerlan/php-imagetiler/releases/tag/3.1.0).

**Comment by pvodicka** [comment]
Oh thank you so much. I really appreciate it.
Unfortunately I see that `ps/image-optimizer` depends on `psr/log` `^1.0` too, so I'm still unable to update :-(

**Comment by codemasher** [comment]
Oh, that's unfortunate, I didn't notice that. It seems the library is unmaintained/abandoned, so I guess I'll have to fork and update it for now. There's still an unfinished optimizer class of my own (to avoid external dependencies...) in my local project but I'm currently busy with other things, so it's not gonna be finished any time soon.

**Comment by codemasher** [comment]
Ok, there you go: [3.2.0](https://github.com/chillerlan/php-imagetiler/releases/tag/3.2.0):

```
   - Removing ps/image-optimizer (2.0.5)
   - Removing symfony/polyfill-php73 (v1.29.0)
   - Locking codemasher/image-optimizer (2.1.0)
   - Upgrading psr/log (1.1.4 => 3.0.0)
   - Upgrading symfony/console (v6.4.4 => v7.0.4)
   - Upgrading symfony/options-resolver (v5.4.21 => v7.0.0)
   - Upgrading symfony/process (v5.4.36 => v7.0.4)
```

I didn't look too hard on the tests and/or outcomes of the dependency update but it seems that nothing explodes. Good luck!

**Comment by pvodicka** [comment]
It's ok, i already did it :-) https://github.com/pvodicka/image-optimizer
Didn't test it yet but for now it's ok for my needs.

**Comment by pvodicka** [comment]
Oh, just wrote the comment :-)

**Comment by codemasher** [comment]
Haha same brain call! Well now you also got an "official" release. Cheers!

**Comment by pvodicka** [comment]
Wow. Thank you :-)
